<template>
  <div>
    <header><NuxtLink to="/" class="brand">ACCOUNT LAB <span>Nuxt × Cognito</span></NuxtLink><NuxtLink to="/account">マイプロフィール</NuxtLink></header>
    <main><NuxtPage /></main>
    <footer>検証用アプリケーション · パスワードはCognitoの画面でのみ入力します。</footer>
  </div>
</template>
<style>
:root{font-family:system-ui,-apple-system,"Noto Sans JP",sans-serif;color:#142c37;background:#f2f6f7;font-synthesis:none}*{box-sizing:border-box}body{margin:0}a{color:#006a71;text-underline-offset:.25em}header{padding:24px max(6vw,24px);display:flex;align-items:center;justify-content:space-between;background:#fff;border-bottom:1px solid #d6e2e5;gap:18px;flex-wrap:wrap}.brand{font-weight:800;letter-spacing:.1em;text-decoration:none}.brand span{font-size:12px;color:#52727b;letter-spacing:0;margin-left:12px}main{max-width:920px;padding:64px 24px;margin:auto;min-height:72vh}h1{font-size:clamp(30px,5vw,48px);line-height:1.35;letter-spacing:-.04em;margin:18px 0 24px}h2{font-size:22px}p{line-height:1.9}.eyebrow{color:#006a71;font-size:12px;font-weight:800;letter-spacing:.13em}.muted{color:#52727b}.card{background:white;border:1px solid #d6e2e5;border-radius:18px;padding:28px;margin-top:28px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:18px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:24px}button,.button{border:0;border-radius:9px;background:#006a71;color:#fff;padding:13px 22px;font:inherit;cursor:pointer;text-decoration:none;display:inline-block;font-weight:650}button.secondary,.button.secondary{color:#006a71;background:#e9f2f3}button:disabled{opacity:.5;cursor:wait}label{display:block;font-weight:650;margin:20px 0 8px}input,select{font:inherit;display:block;width:100%;padding:13px;border:1px solid #94adb3;border-radius:8px;background:white;color:#142c37}input:focus,select:focus,button:focus-visible,a:focus-visible{outline:3px solid #e6ae39;outline-offset:3px}.status{padding:13px 16px;border-radius:9px;background:#e9f2f3;margin-top:18px}.error{background:#fff0ef;color:#982d2d}code{background:#e9f2f3;padding:3px 7px;border-radius:5px;font-size:.9em}footer{text-align:center;padding:24px;color:#52727b;font-size:12px;border-top:1px solid #d6e2e5}@media(max-width:550px){main{padding-top:36px}.card{padding:20px}.brand span{display:block;margin:5px 0}}
</style>
